// recipe.interface.ts

export interface Recipe {
    _id: string; // autogenerated by mongodb
    title: string; // required field with minimum 5 characters
    description: string; // required field
    ingredients: Ingredient[]; // recipe can have one or more ingredients
    instructions: Instruction[]; // recipe can have one or more instructions
    tags: string[]; // recipe can have one or more tags or keywords
    imagePath: string; // optional field
    rating: number; // optional
    category: string; //optional
    comments: string; //optional
}

export interface Ingredient {
    name: string;  // required field with minimum 5 characters
    quantity: string; // required field with minimum 1 characters
    measurement: string; // required field with minimum 3 characters
}

export interface Instruction {
    order: number; // required field to provide sort order for instructions
    direction: string;   // required field with minimum 5 characters
}
